# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller 规格文件 - Minecraft Launcher"""

import os
import sys
from pathlib import Path

block_cipher = None

project_root = Path(os.getcwd())
src_path = project_root / "src"
main_script = project_root / "main.py"
icon_path = project_root / "assets" / "icons" / "icon.ico"

if not icon_path.exists():
    icon_path = None

excludes = [
    "tkinter",
    "unittest",
    "pydoc",
    "doctest",
    "pdb",
    "profile",
    "pstats",
    "cProfile",
    "curses",
    "lib2to3",
    "distutils",
    "setuptools",
    "pip",
    "wheel",
    "IPython",
    "jupyter",
    "notebook",
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "cv2",
    "pytest",
    "black",
    "flake8",
    "mypy",
    "coverage",
    "tox",
]

hiddenimports = [
    "src",
    "src.core",
    "src.core.launcher",
    "src.core.java_detector",
    "src.core.account",
    "src.core.bundled_jre",
    "src.core.renderer",
    "src.core.server_manager",
    "src.core.server_ping",
    "src.core.skin_manager",
    "src.core.auth",
    "src.utils",
    "src.utils.logger",
    "src.utils.config",
    "src.utils.file_utils",
    "src.utils.http_utils",
    "src.utils.network",
    "src.utils.crash_handler",
    "src.utils.updater",
    "src.utils.backup",
    "src.utils.download_source",
    "src.version",
    "src.version.api",
    "src.version.downloader",
    "src.version.asset_manager",
    "src.version.version_manager",
    "src.version.manager",
    "src.version.metadata",
    "src.modloader",
    "src.modloader.base",
    "src.modloader.forge",
    "src.modloader.fabric",
    "src.modloader.quilt",
    "src.modloader.manager",
    "src.modloader.maven_utils",
    "src.modloader.mod_manager",
    "src.modloader.modrinth",
    "src.account",
    "src.ui",
    "src.ui.main_window",
    "src.ui.settings_dialog",
    "src.ui.download_dialog",
    "src.ui.account_dialog",
    "src.ui.first_run_wizard",
    "src.ui.game_log_window",
    "src.ui.java_manager",
    "src.ui.add_server_dialog",
    "src.ui.server_page",
    "src.ui.skin_dialog",
    "src.ui.mod_download_dialog",
    "src.ui.mod_manager_dialog",
    "src.ui.modloader_install_dialog",
    "src.ui.microsoft_login_dialog",
    "src.ui.styles",
    "src.ui.styles.theme_manager",
    "src.ui.widgets",
    "src.ui.widgets.title_bar",
    "src.ui.widgets.dialog_title_bar",
    "src.ui.widgets.card_widget",
    "src.ui.widgets.toast",
    "src.ui.widgets.loading_spinner",
    "src.ui.widgets.download_item",
    "src.ui.widgets.version_list_item",
    "src.ui.widgets.player_avatar",
    "src.ui.resources",
    "PyQt6",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.QtNetwork",
    "PyQt6.sip",
    "requests",
    "urllib3",
    "urllib3.util",
    "urllib3.util.ssl_",
    "urllib3.packages",
    "urllib3.packages.ssl_match_hostname",
    "certifi",
    "charset_normalizer",
    "idna",
    "email",
    "email.mime",
    "email.mime.text",
    "email.mime.multipart",
    "email.mime.base",
    "email.parser",
    "email.utils",
    "email.header",
    "email.charset",
    "email.encoders",
    "http",
    "http.client",
    "http.cookiejar",
    "http.cookies",
    "ssl",
    "hmac",
    "hashlib",
    "secrets",
    "json",
    "zipfile",
    "tarfile",
    "xml",
    "xml.etree",
    "xml.etree.ElementTree",
    "logging",
    "logging.handlers",
    "platform",
    "ctypes",
    "ctypes.wintypes",
    "winreg",
    "msvcrt",
    "tomllib",
    "argparse",
    "difflib",
    "concurrent",
    "concurrent.futures",
    "multiprocessing",
    "html",
    "html.parser",
    "pyexpat",
    "xml.parsers",
    "xml.parsers.expat",
]

a = Analysis(
    [str(main_script)],
    pathex=[str(src_path), str(project_root)],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="MCLauncher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        "vcruntime140.dll",
        "python3*.dll",
        "Qt6*.dll",
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(icon_path) if icon_path else None,
    version="assets/version_info.txt" if (project_root / "assets" / "version_info.txt").exists() else None,
)
